[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "viewer"  # Versteckt Dev Menü
showErrorDetails = false # Versteckt technische Fehler-Stacks vor dem User

[theme]
base = "light"           # Erzwingt helles Design 
primaryColor = "#1C4E80" # "Polizei-Blau" für Buttons